### PR TITLE
Planning on publishing to OSSRH

### PR DESCRIPTION
**Pull request by lewismc**
Hi @otrack this pull request is a first attempt at adding required pom.xml configuration such that a release will be accepted by the QA tests undertaken when we publish artifacts to OSSRH as described within http://central.sonatype.org/pages/ossrh-guide.html

### CODE REVIEW

**Comment by vschiavoni** [comment]
Hello @lewismc thanks for this PR ! 
One question: why the PR suggests <version>7.2.5.Final-SNAPSHOT</version> instead of <version>7.2.5.Final</version>  ?

**Comment by lewismc** [comment]
Hi Valerio,
This SNAPSHOT convention is required by the Maven release plugin as it
build off of the notion that the codebase, prior to release, is in a
SNaPSHOT state and you can therefore deploy and distribute SNAPSHOTs,
however when you come to a release the SNaPSHoT is removed and the actual
version is deployed.
In addition, once the release artifacts have been deployed, the plugin then
appends a new SNaPSHOT version and let's you continue working in your new
Development drive.
More can be found here
https://maven.apache.org/guides/mini/guide-releasing.html
Thanks

On Tuesday, March 29, 2016, Valerio Schiavoni notifications@github.com
wrote:

> Hello @lewismc https://github.com/lewismc thanks for this PR !
> One question: why the PR suggests 7.2.5.Final-SNAPSHOT instead of
> 7.2.5.Final ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/leads-project/infinispan-avro/pull/2#issuecomment-202768876

## 

_Lewis_

**Comment by lewismc** [comment]
@vschiavoni can you please merge?
Are you maintaining this library now? I really don't want this module to be unmaintained and would really like to work with you on ensuring we can consume the gora-infinispan module within Gora. That module relies upon this dependency being available.

**Comment by lewismc** [comment]
As I am not able to push the tag to this repository e.g. I don't have write permissions, then i can't make the release with the SCM label being github.com:leads-project/infinispan-avro.git

**Comment by vschiavoni** [comment]
Merged, thanks !

**Comment by lewismc** [comment]
Excellent. Do you want to be added to the release profile in Sonatype so
you can release this project and we can consume the artifacts?

On Saturday, April 9, 2016, Valerio Schiavoni notifications@github.com
wrote:

> Merged, thanks !
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/leads-project/infinispan-avro/pull/2#issuecomment-207893173

## 

_Lewis_

**Comment by vschiavoni** [comment]
Better add me and @otrack as well.

**Comment by lewismc** [comment]
Cool. Can you please comment over on
https://issues.sonatype.org/browse/OSSRH-21457 with your usernames and let
Joel know?

On Sunday, April 10, 2016, Valerio Schiavoni notifications@github.com
wrote:

> Better add me and @otrack https://github.com/otrack as well.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/leads-project/infinispan-avro/pull/2#issuecomment-208014891

## 

_Lewis_

**Comment by lewismc** [comment]
@otrack @vschiavoni are you able to comment with your usernames over on https://issues.sonatype.org/browse/OSSRH-21457  ? This is the only way that this project can publish artifacts to OSSRH. There is a workaround e/g/ if I clone the code and do it myself, however I would rather that you guys were part of the process.
Thanks

**Comment by vschiavoni** [comment]
I've added a comment there.

**Comment by lewismc** [comment]
Thank you. Thanks for reply.

On Tue, Apr 19, 2016 at 9:37 AM, Valerio Schiavoni <notifications@github.com

> wrote:
> 
> I've added a comment there.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/leads-project/infinispan-avro/pull/2#issuecomment-212009038

## 

_Lewis_

**Comment by lewismc** [comment]
@vschiavoni, now you have been granted permissions to publish the artifacts to OSSRH.
Can you please run the following

```
mvn release:clean release:prepare -DautoVersionSubmodules=true
```

The above will allow you to view the actual release artifacts prior to release.
If you are happy with them then please execute

```
mvn release:perform
```

This does the following
1) pushes the maven artifacts to a staging repository at https://oss.sonatype.org/
2) creates a release tag in https://github.com/leads-project/infinispan-avro which you can view.
3) finally, it commits the update of all module artifacts within the infinispan-avro pom.xml files and commits these to master so we can continue with development e.g. bumps to the next development SNAPSHOT.

Once this is completed,
1) navigate to https://oss.sonatype.org/ and log in.
2) click on _Staging Repositories_ on the left hand side, you should see the infinispan-avro release canidate staging profile
3) Select the profile and close the staging profile. This makes the artifacts available for people to tests (if required), you can then also release the profile which will formally release the artifacts and soon they will be available within Maven Cebtral once they are shadowed over.

If you have any issues then please let me know here and I can help out. Thanks

**Comment by otrack** [comment]
The first phase is ok  (mvn release:clean release:prepare -DautoVersionSubmodules=true), but unfortunately when i am deploying the artifact (mvn release:perform), it fails saying:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.5:deploy (default-deploy) on project infinispan-avro: Failed to deploy artifacts: Could not transfer artifact org.infinispan:infinispan-avro:pom:7.2.5.Final-20160425.110808-1 from/to jboss-snapshots-repository (https://repository.jboss.org/nexus/content/repositories/snapshots/): Failed to transfer file: https://repository.jboss.org/nexus/content/repositories/snapshots/org/infinispan/infinispan-avro/7.2.5.Final-SNAPSHOT/infinispan-avro-7.2.5.Final-20160425.110808-1.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

Any idea how to fix this ? Thanks.

**Comment by otrack** [comment]
Ok, so i fixed the pom.xml, adding the appropriate distributedmanagement configuration. Still, I have a problem, as I do not have access to publish all the modules that this project contains on sonatype. I just asked for it.

**Comment by otrack** [comment]
This is fine now, and the artifacts are available in their snapshot versions.

**Pull request merged**
